version: 2.1
#####################################################
# Anchors
#####################################################
defaults: &defaults
  docker:
  - image: circleci/node:latest

  working_directory: ~/project
gcp_defaults: &gcp_defaults
  docker:
    - image: google/cloud-sdk
  working_directory: ~/project
#####################################################
# Common Commands
#####################################################
# TODO: Author a private Orb. Status: CircleCI feature avaliation
# Specific CI commands should be setup as an anchor.
commands:
  apt_repo_update:
    description: update/fix apt repository
    steps:
      - run:
          name: Update Apt Repository
          command: |
            #Fix issue with Debian Jessie that prevents to update the repository
            printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list
            echo -n "#deb http://deb.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
            apt-get update

  notify:
    description: Send notification to Symphony using universal web hook
    parameters:
      webhookurl:
        description: The web hook url to use. Can be bound to an env var
        type: string
      data_template:
        description: Message template file in json format.
        type: string
      message_template:
        description: MessageML file used to send message
        type: string
      make_notification:
        description: Defines if notification should be sent.
        type: string
        default: "true"
    steps:
      - when:
          condition: << parameters.make_notification >>
          steps:
            - run:
                name: Send Notification
                command: |
                  if [ "<< parameters.make_notification >>" == "true" ];then
                    apt-get install -qq -y gettext 
                    envsubst < << parameters.data_template >> > ./.circleci/data.json
                    curl -X POST -H "Content-Type:multipart/form-data" \
                    -F 'data=@./.circleci/data.json' \
                    -F 'message=@<< parameters.message_template >>' << parameters.webhookurl >>
                  fi
#####################################################
# Jobs
#####################################################
jobs:
  lint_and_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
           - v1-dependencies-{{ checksum "package.json" }}
           - v1-dependencies-
      - run:
          name: Dependencies Install
          command: |
           npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - run:
      #     name: Lint
      #     command: |
      #       npm run lint
      # - run:
      #     name: Test package
      #     command: |
      #       npm run test

      # - run:
      #     name: Run Coverage
      #     command: |
      #       npm run test:coverage || true
      - persist_to_workspace:
          root: ~/project
          paths:
            - .circleci
            # - coverage
            # - test-report.xml
  sonarqube_analysis:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: SonarQube Analysis Dependencies
          command: |
            sudo apt-get install -qq -y gettext

            curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip \
              -o sonar-scanner-cli-3.3.0.1492-linux.zip
            unzip sonar-scanner-cli-3.3.0.1492-linux.zip

            envsubst < .circleci/templates/sonar-project.properties.tpl > sonar-project.properties

            envsubst < .circleci/templates/sonar-scanner.properties.tpl > sonar-scanner-3.3.0.1492-linux/conf/sonar-scanner.properties
      - run:
          name: Run SonarQube Analysis
          command: |
            chmod +x ./sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner

            ./sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner
      # - run:
      #     name: Get Test Result
      #     command: |
      #       source ./.circleci/scripts/test-result
      - persist_to_workspace:
          root: ~/project
          paths:
          - .circleci

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Publish package
          command: |
            echo ${APPROVAL_USERS}


            for USERS in "${APPROVAL_USERS[@]}"; do
                if [[ ${USERS} == \"${CIRCLE_USERNAME}\" ]]; then
                  echo "publish"
                  npm publish --access private --dry-run
                  exit 0
                fi
            done
            
  notify_npm_publish:
    <<: *gcp_defaults
    steps:
      - attach_workspace:
          at: ~/project
      - notify:
          webhookurl: ${NOTIFICATION_WEBHOOK}
          data_template: "./.circleci/data.json.tpl"
          message_template: "./.circleci/message.xml"
          make_notification: ${PUBLISH_TO_NPM}

#####################################################
# Workflow
#####################################################
workflows:
  version: 2
  weakly_code_analysis:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - lint_and_test
      - sonarqube_analysis:
          requires:
            - lint_and_test

  npm_publish:
    jobs:
      - sonarqube_analysis
      - lint_and_test:
          requires:
            - sonarqube_analysis
      - publish:
          type: approval
          requires:
            - lint_and_test
          filters:
            branches:
              only: 
                - master
                - feature/npm-publish-data
      - notify_npm_publish:
          requires:
            - publish